# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_mycourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourse',
            options={'verbose_name': 'My courses', 'verbose_name_plural': 'My courses'},
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='owned', to='courses.Course'),
        ),
    ]
